package com.hoster.files;

import com.hoster.data.Host;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class HostsFile extends ConfigFile
{
    public List<Host> load(String fileName)
    {
        List<Host> hostsList = new ArrayList<>();
        File file = new File(fileName);
        Host h;

        try {
            if (file.exists()) {
                Scanner reader = new Scanner(file);
                while (reader.hasNextLine()) {
                    String[] line = reader.nextLine().split(" ");
                    if (line.length == 2) {
                        h = new Host();
                        h.setActive(isHostActive(line[0].trim()));
                        h.setIp(line[0].trim().replaceAll("#", ""));
                        h.setDomain(line[1].trim());

                        hostsList.add(h);
                    }
                }
                reader.close();
            }
        } catch (FileNotFoundException e) {
            consoleListener.onConsoleError(e.getMessage());
        }

        return hostsList;
    }

    public boolean save(String fileName, List<Host> hostsList, String appName, String appVersion)
    {
        if (deleteCurrentFile(fileName)) {
            if (createNewFile(fileName)) {
                return writeFile(fileName, hostsList, appName, appVersion);
            }
        }
        return false;
    }

    private boolean writeFile(String fileName, List<Host> hostsList, String appName, String appVersion)
    {
        try {
            if (!hostsList.isEmpty()) {
                FileWriter fileWriter = new FileWriter(fileName);
                fileWriter.write("# Generated by " + appName + " " + appVersion + "\n");
                String ip;

                for (Host h : hostsList) {
                    ip = (!h.isActive() ? "#" : "") + h.getIp();
                    fileWriter.write(ip + " " + h.getDomain() + "\n");
                }
                fileWriter.close();
                return true;
            }
        } catch (IOException e) {
            consoleListener.onConsoleError(e.getMessage());
        }
        return false;
    }

    private boolean isHostActive(String ip)
    {
        return ip.charAt(0) != '#';
    }
}
