package com.hoster.files;

import java.util.HashMap;
import java.util.Map;

public class Hosts
{
    public static Map<String, String> load(String fileName)
    {
        return new ConfigFile().load(fileName, getEmptyHosts(), " ");
    }

    public static boolean save(String fileName, Map<String, String> hosts, String appName, String appVersion)
    {
        return new ConfigFile().save(fileName, "Generated by " + appName + " " + appVersion, " ", hosts);
    }

    private static Map<String, String> getEmptyHosts()
    {
        return new HashMap<>();
    }
}
