package com.hoster.files;

import com.hoster.Host;

import java.util.HashMap;
import java.util.Map;

public class HostsFile
{
    public static Map<String, Host> load(String fileName)
    {
        Map<String, String> hostFile = new ConfigFile().load(fileName, " ");
        Map<String, Host> hostsMap = new HashMap<>();
        Host host;

        for (Map.Entry<String, String> entry : hostFile.entrySet()) {
            host = new Host();
            host.setActive(isHostActive(entry.getKey()));
            host.setIp(entry.getKey());
            host.setDomain(entry.getValue());

            hostsMap.put(host.getIp(), host);
        }

        return hostsMap;
    }

    public static boolean save(String fileName, Map<String, Host> hostsMap, String appName, String appVersion)
    {
        Map<String, String> hostFile = new HashMap<>();
        Host host;
        String ip;

        for (Map.Entry<String, Host> entry : hostsMap.entrySet()) {
            host = entry.getValue();
            ip = (!host.isActive() ? "#" : "") + host.getIp();

            hostFile.put(ip, host.getDomain());
        }

        return new ConfigFile().save(fileName, "Generated by " + appName + " " + appVersion, " ", hostFile);
    }

    private static boolean isHostActive(String ip)
    {
        return ip.charAt(0) != '#';
    }
}
